import { Flight, CarrierKpi } from "./types";

export const MOCK_FLIGHTS: Flight[] = [
  {
    id: "1",
    flightNumber: "QF1",
    carrier: "Qantas",
    origin: "Dubai (DXB)",
    destination: "London Heathrow (LHR)",
    scheduledTime: "06:10",
    estimatedTime: "06:10",
    gate: "B32",
    stand: "Stand 512",
    status: "ARRIVED",
    team: "Alpha",
    turnaroundMinutes: 90,
    elapsedMinutes: 74,
    aircraft: "Airbus A380",
    pax: 421,
    kpiBreached: false,
  },
  {
    id: "2",
    flightNumber: "LH902",
    carrier: "Lufthansa",
    origin: "Frankfurt (FRA)",
    destination: "London Heathrow (LHR)",
    scheduledTime: "07:45",
    estimatedTime: "08:10",
    gate: "A14",
    stand: "Stand 308",
    status: "DELAYED",
    team: "Bravo",
    turnaroundMinutes: 60,
    elapsedMinutes: 67,
    aircraft: "Airbus A320",
    pax: 168,
    kpiBreached: true,
  },
  {
    id: "3",
    flightNumber: "BA117",
    carrier: "British Airways",
    origin: "New York (JFK)",
    destination: "London Heathrow (LHR)",
    scheduledTime: "08:00",
    estimatedTime: "08:00",
    gate: "C22",
    stand: "Stand 401",
    status: "BOARDING",
    team: "Charlie",
    turnaroundMinutes: 75,
    elapsedMinutes: 58,
    aircraft: "Boeing 777-300",
    pax: 295,
    kpiBreached: false,
  },
  {
    id: "4",
    flightNumber: "EK004",
    carrier: "Emirates",
    origin: "Dubai (DXB)",
    destination: "London Heathrow (LHR)",
    scheduledTime: "08:30",
    estimatedTime: "08:30",
    gate: "B18",
    stand: "Stand 522",
    status: "ON_TIME",
    team: "Alpha",
    turnaroundMinutes: 90,
    elapsedMinutes: 22,
    aircraft: "Airbus A380",
    pax: 489,
    kpiBreached: false,
  },
  {
    id: "5",
    flightNumber: "VS401",
    carrier: "Virgin Atlantic",
    origin: "Los Angeles (LAX)",
    destination: "London Heathrow (LHR)",
    scheduledTime: "09:15",
    estimatedTime: "09:45",
    gate: "D05",
    stand: "Stand 210",
    status: "DELAYED",
    team: "Delta",
    turnaroundMinutes: 80,
    elapsedMinutes: 88,
    aircraft: "Airbus A350-1000",
    pax: 321,
    kpiBreached: true,
  },
  {
    id: "6",
    flightNumber: "IB3163",
    carrier: "Iberia",
    origin: "Madrid (MAD)",
    destination: "London Heathrow (LHR)",
    scheduledTime: "09:50",
    estimatedTime: "09:50",
    gate: "A07",
    stand: "Stand 115",
    status: "ON_TIME",
    team: "Bravo",
    turnaroundMinutes: 55,
    elapsedMinutes: 30,
    aircraft: "Airbus A321",
    pax: 194,
    kpiBreached: false,
  },
  {
    id: "7",
    flightNumber: "AA100",
    carrier: "American Airlines",
    origin: "Chicago (ORD)",
    destination: "London Heathrow (LHR)",
    scheduledTime: "10:20",
    estimatedTime: "10:20",
    gate: "C11",
    stand: "Stand 319",
    status: "DEPARTED",
    team: "Charlie",
    turnaroundMinutes: 70,
    elapsedMinutes: 70,
    aircraft: "Boeing 787-9",
    pax: 243,
    kpiBreached: false,
  },
  {
    id: "8",
    flightNumber: "SQ318",
    carrier: "Singapore Airlines",
    origin: "Singapore (SIN)",
    destination: "London Heathrow (LHR)",
    scheduledTime: "11:00",
    estimatedTime: "11:25",
    gate: "B41",
    stand: "Stand 548",
    status: "CANCELLED",
    team: "Delta",
    turnaroundMinutes: 85,
    elapsedMinutes: 0,
    aircraft: "Airbus A350-900",
    pax: 0,
    kpiBreached: false,
  },
];

export const CARRIER_KPI_DATA: CarrierKpi[] = [
  { carrier: "Qantas", target: 90, actual: 84 },
  { carrier: "Lufthansa", target: 60, actual: 71 },
  { carrier: "British Airways", target: 75, actual: 73 },
  { carrier: "Emirates", target: 90, actual: 88 },
  { carrier: "Virgin Atlantic", target: 80, actual: 93 },
  { carrier: "American Airlines", target: 70, actual: 68 },
];
