import { time } from "console";
import { Flight, CarrierKpi } from "./types";

function generateFlights(): Flight[] {
  const now = new Date();

  // Helper to create a time string offset by minutes from now
  function timeOffset(minutesFromNow: number): string {
    const d = new Date(now.getTime() + minutesFromNow * 60000);
    return d.toLocaleTimeString("en-GB", {
      hour: "2-digit",
      minute: "2-digit",
      timeZone: "Europe/London",
    });
  }

  return [
    {
      id: "1",
      flightNumber: "QF1",
      carrier: "Qantas",
      origin: "Dubai (DXB)",
      destination: "London Heathrow (LHR)",
      scheduledTime: timeOffset(-90),
      estimatedTime: timeOffset(-90),
      atd: timeOffset(-90),
      delayMinutes: 0,
      gate: "B32",
      stand: "Stand 512",
      status: "DEPARTED",
      team: "Alpha",
      turnaroundMinutes: 90,
      elapsedMinutes: 74,
      aircraft: "Airbus A380",
      pax: 421,
      kpiBreached: false,
    },
    {
      id: "2",
      flightNumber: "LH902",
      carrier: "Lufthansa",
      origin: "Frankfurt (FRA)",
      destination: "London Heathrow (LHR)",
      scheduledTime: timeOffset(-60),
      estimatedTime: timeOffset(-45),
      atd: timeOffset(-40),
      delayMinutes: 20,
      gate: "A14",
      stand: "Stand 308",
      status: "DEPARTED",
      team: "Bravo",
      turnaroundMinutes: 60,
      elapsedMinutes: 67,
      aircraft: "Airbus A320",
      pax: 168,
      kpiBreached: true,
    },
    {
      id: "3",
      flightNumber: "BA117",
      carrier: "British Airways",
      origin: "New York (JFK)",
      destination: "London Heathrow (LHR)",
      scheduledTime: timeOffset(+10),
      estimatedTime: timeOffset(+10),
      atd: null,
      delayMinutes: 0,
      gate: "C22",
      stand: "Stand 401",
      status: "BOARDING",
      team: "Charlie",
      turnaroundMinutes: 75,
      elapsedMinutes: 62,
      aircraft: "Boeing 777-300",
      pax: 295,
      kpiBreached: false,
    },
    {
      id: "4",
      flightNumber: "EK004",
      carrier: "Emirates",
      origin: "Dubai (DXB)",
      destination: "London Heathrow (LHR)",
      scheduledTime: timeOffset(20),
      estimatedTime: timeOffset(20),
      atd: null,
      delayMinutes: 0,
      gate: "B18",
      stand: "Stand 522",
      status: "ON_TIME",
      team: "Alpha",
      turnaroundMinutes: 90,
      elapsedMinutes: 10,
      aircraft: "Airbus A380",
      pax: 489,
      kpiBreached: false,
    },
    {
      id: "5",
      flightNumber: "VS401",
      carrier: "Virgin Atlantic",
      origin: "Los Angeles (LAX)",
      destination: "London Heathrow (LHR)",
      scheduledTime: timeOffset(+30),
      estimatedTime: timeOffset(+35),
      atd: null,
      delayMinutes: 0,
      gate: "D05",
      stand: "Stand 210",
      status: "DELAYED",
      team: "Delta",
      turnaroundMinutes: 80,
      elapsedMinutes: 88,
      aircraft: "Airbus A350-1000",
      pax: 321,
      kpiBreached: true,
    },
    {
      id: "6",
      flightNumber: "IB3163",
      carrier: "Iberia",
      origin: "Madrid (MAD)",
      destination: "London Heathrow (LHR)",
      scheduledTime: timeOffset(40),
      estimatedTime: timeOffset(40),
      atd: null,
      delayMinutes: 0,
      gate: "A07",
      stand: "Stand 115",
      status: "ON_TIME",
      team: "Bravo",
      turnaroundMinutes: 55,
      elapsedMinutes: 20,
      aircraft: "Airbus A321",
      pax: 194,
      kpiBreached: false,
    },
    {
      id: "7",
      flightNumber: "AA100",
      carrier: "American Airlines",
      origin: "Chicago (ORD)",
      destination: "London Heathrow (LHR)",
      scheduledTime: timeOffset(80),
      estimatedTime: timeOffset(80),
      atd: null,
      delayMinutes: 0,
      gate: "C11",
      stand: "Stand 319",
      status: "ON_TIME",
      team: "Charlie",
      turnaroundMinutes: 70,
      elapsedMinutes: 45,
      aircraft: "Boeing 787-9",
      pax: 243,
      kpiBreached: false,
    },
    {
      id: "8",
      flightNumber: "SQ318",
      carrier: "Singapore Airlines",
      origin: "Singapore (SIN)",
      destination: "London Heathrow (LHR)",
      scheduledTime: timeOffset(100),
      estimatedTime: timeOffset(200),
      atd: null,
      delayMinutes: 0,
      gate: "B41",
      stand: "Stand 548",
      status: "CANCELLED",
      team: "Delta",
      turnaroundMinutes: 85,
      elapsedMinutes: 0,
      aircraft: "Airbus A350-900",
      pax: 0,
      kpiBreached: false,
    },
  ];
}

export { generateFlights };

export const CARRIER_KPI_DATA: CarrierKpi[] = [
  { carrier: "Qantas", target: 90, actual: 84 },
  { carrier: "Lufthansa", target: 60, actual: 71 },
  { carrier: "British Airways", target: 75, actual: 73 },
  { carrier: "Emirates", target: 90, actual: 88 },
  { carrier: "Virgin Atlantic", target: 80, actual: 93 },
  { carrier: "American Airlines", target: 70, actual: 68 },
];
